### ISSUE TITLE
Calls `exit(1)` if unable to initialize C++ XMP Toolkit

### ISSUE THREAD

**Issue by scouten-adobe** [adobe/xmp-toolkit-rs#100]
### Expected Behaviour

If C++ XMP Toolkit fails to initialize (a rare case), further functions should return a corresponding `XmpError` status.

### Actual Behaviour

If C++ XMP Toolkit fails to initialize, causes immediate program termination via `exit(1)`.

**Comment by scouten-adobe** [comment]
See function `init_xmp_fn` at beginning of ffi.cpp.

**Comment by crandmck** [comment]
@adobe export issue to Jira project CAI
