### ISSUE TITLE
DISCUSS: How to compare `XmpDateTime` values?

### ISSUE THREAD

**Issue by scouten-adobe** [adobe/xmp-toolkit-rs#150]
There is currently no mechanism for comparing `XmpDateTime` values.

I've held off on this because I can't find an appropriate mapping between the Rust `Ord` or `PartialOrd` traits and the C++ implementation of `TXMPUtils::CompareDateTime` which:

* treats dates as equivalent if one has a time zone and the other does not
* is ambiguous about how it compares date/time values that are missing either date or time

Advice on how or whether to attempt such a mapping would be welcome.

**Comment by crandmck** [comment]
@adobe export issue to Jira project CAI

**Comment by scouten-adobe** [comment]
I'm not sure it's possible to solve this issue in a meaningful way and I've not seen any discussion. Closing for now; if anyone needs this to work, please reopen and add some suggestions on how to address the issues flagged above.
