### ISSUE TITLE
Not building on slim unix images

### ISSUE THREAD

**Issue by tmccavana** [adobe/xmp-toolkit-rs#202]
### Expected Behaviour

I am trying to install c2patool in a slim or alpine image and it seems there is an unmet dependency in the minimalist linux environments (e.g. Alpine or slim). 

**_Note the build works fine on full Debian images_** - I was just hoping to determine the missing dependency and document it somewhere. 

### Actual Behaviour

The c2patool fails on the xmp-toolkit depency build.

```
19.40    Compiling url v2.5.0
19.52 error: failed to run custom build command for `xmp_toolkit v1.7.2`
19.52 
19.52 Caused by:
19.52   process didn't exit successfully: `/tmp/cargo-installdmthm9/release/build/xmp_toolkit-ea6102d1f97c07bc/build-script-build` (exit status: 101)
19.52   --- stdout
19.52   cargo:rerun-if-changed=build.rs
19.52   > git submodule init
19.52 
19.52 
19.52   --- stderr
19.52   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/xmp_toolkit-1.7.2/build.rs:381:10:
19.52   called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
19.52   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````

#### Steps to Reproduce

This dockerfile should allow you to reproduce the issue. 

```
## Use a Rust image 
FROM rust:1.76-slim-bullseye

# Set the working directory in the container
WORKDIR /app

# Install necessary dependencies for installing Rust and c2patool
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
        build-essential \
        libssl-dev \
        pkg-config \
        && rm -rf /var/lib/apt/lists/*

# Install Rust using Rustup
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Add cargo to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

# Install c2patool using cargo
RUN cargo install c2patool
```

#### Platform and Version

Minimally, have reproduced the bug on slim-bookworm, slim-bullseye and alpine3.19 images 
Build works fine on full Debian images

Not a critical issue. Let me know if you need more information

**Comment by scouten-adobe** [comment]
Looks like the same issue as #175, which should be fixed with the 1.7.3 release (in release process now).

Please re-open if that version doesn't fix your issue.
