### ISSUE TITLE
Warnings generated while publishing this crate

### ISSUE THREAD

**Issue by scouten-adobe** [adobe/xmp-toolkit-rs#92]
Several warnings are now generated when publishing this crate due to [GitHub's recent announcement deprecating set-output command](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

This is a tracking issue while action step authors respond to that issue.

**Comment by scouten-adobe** [comment]
See log output here: https://github.com/adobe/xmp-toolkit-rs/actions/runs/3291504965/jobs/5425744060#step:6:13

**Comment by scouten-adobe** [comment]
Related issues:

* https://github.com/actions-ecosystem/action-get-latest-tag/issues/25
* https://github.com/PaulHatch/semantic-version/issues/66
* https://github.com/mathiasvr/command-output/issues/4
* https://github.com/stefanzweifel/git-auto-commit-action/issues/250

**Comment by crandmck** [comment]
@adobe export issue to Jira project CAI

**Comment by scouten-adobe** [comment]
I've been able to update or replace all of the deps to new versions that don't have the warnings.. Closing.
